// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpHu7-XwxLYu_knEez256LQs7TmTdWU44',
    appId: '1:712704718293:web:8025c3071a8ccb06dd395c',
    messagingSenderId: '712704718293',
    projectId: 'coffee-lab-6b2d2',
    authDomain: 'coffee-lab-6b2d2.firebaseapp.com',
    storageBucket: 'coffee-lab-6b2d2.firebasestorage.app',
    measurementId: 'G-R5WFKVJXQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-CgtFPkQgsaTWNpYk7ha_RJHpL_E4C3I',
    appId: '1:712704718293:android:fbe0f768550b7ec8dd395c',
    messagingSenderId: '712704718293',
    projectId: 'coffee-lab-6b2d2',
    storageBucket: 'coffee-lab-6b2d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXBBCcYGL2tp-FdhTKLk9f8e0Dh_qbqIE',
    appId: '1:712704718293:ios:a9ff46bc310b7b9ddd395c',
    messagingSenderId: '712704718293',
    projectId: 'coffee-lab-6b2d2',
    storageBucket: 'coffee-lab-6b2d2.firebasestorage.app',
    iosBundleId: 'com.example.CoffeeLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXBBCcYGL2tp-FdhTKLk9f8e0Dh_qbqIE',
    appId: '1:712704718293:ios:a9ff46bc310b7b9ddd395c',
    messagingSenderId: '712704718293',
    projectId: 'coffee-lab-6b2d2',
    storageBucket: 'coffee-lab-6b2d2.firebasestorage.app',
    iosBundleId: 'com.example.CoffeeLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpHu7-XwxLYu_knEez256LQs7TmTdWU44',
    appId: '1:712704718293:web:54af0f4f8deeb1f7dd395c',
    messagingSenderId: '712704718293',
    projectId: 'coffee-lab-6b2d2',
    authDomain: 'coffee-lab-6b2d2.firebaseapp.com',
    storageBucket: 'coffee-lab-6b2d2.firebasestorage.app',
    measurementId: 'G-WN22V2NXKF',
  );
}
